### ISSUE TITLE
Not showing all sensors

### ISSUE THREAD

**Issue by BernhardBuckel** [hthiery/python-lacrosse#2]
Hi, 
i switched from a former implementation on fhem to home assistant and not all of my lacrosse sensors are showing up. In my old setup i realized that the ids are sometimes not only integers (e.g. 3E). When using the CLI only 2 of the 4 are showing up. I tried to debug your code and had a look and the regexp and couldn't figure out what's going wrong. do you have an idea?

**Comment by hthiery** [comment]
could you please connect the jeelink directly to the serial and log the output without running the pylacrosse cli and without any other tools like homeassistanst?

then we should figure out what's going wrong.

**Comment by BernhardBuckel** [comment]
sorry I'm pretty new to python. can you give me a hint how to do that?

**Comment by hthiery** [comment]
You dont need Python. Just connect the jeelink to the serial of your computer and start a terminal program. E.g. PuTTY on windows or minicom in Linux. Baudrate should be 57600.

**Comment by hthiery** [comment]
You could also use this python script:

https://gist.github.com/hthiery/4d225e8c233075ecf45f4fed4ac87753

**Comment by BernhardBuckel** [comment]
It's a USB device, I can't connect to the serial port?

**Comment by hthiery** [comment]
yes but on the module it is a usb<->serial device. so in your OS you see a serial device

**Comment by BernhardBuckel** [comment]
checked with minicom with baudrate 57600. Output is as follows
OK 9 6 1 4 178 61
OK 9 6 1 4 177 61
OK 9 51 1 4 80 49
OK 9 6 1 4 178 61
OK 9 6 1 4 177 61
OK 9 6 1 4 178 61
OK 9 6 1 4 177 61
OK 9 51 1 4 80 49
OK 9 6 1 4 177 61
OK 9 51 1 4 80 49
OK 9 6 1 4 178 61
OK 9 6 1 4 178 61
OK 9 6 1 4 178 61
OK 9 6 1 4 177 61
OK 9 51 1 4 80 49
OK 9 6 1 4 177 61
OK 9 6 1 4 177 61
OK 9 51 1 4 80 49
OK 9 6 1 4 178 61
OK 9 6 1 4 177 61
OK 9 6 1 4 178 61
OK 9 51 1 4 80 49
OK 9 6 1 4 178 61
OK 9 6 1 4 178 61
OK 9 51 1 4 80 49
OK 9 6 1 4 178 61
OK 9 6 1 4 178 61
OK 9 51 1 4 80 49
OK 9 6 1 4 178 61
OK 9 6 1 4 178 61
OK 9 51 1 4 80 49
OK 9 6 1 4 178 61

**Comment by hthiery** [comment]
The output shows only 2 sensors.

**Comment by hthiery** [comment]
Can I close this issue?
