### ISSUE TITLE
Support for TX35DTH-IT

### ISSUE THREAD

**Issue by deveth0** [hthiery/python-lacrosse#3]
Hi,
I am using your library as part of the home-assistant system I installed and wanted to include my TX35DTH Lacrosse sensors. 
I had to modify the FHEM Sketch for the JeeLink Stick to use the 9579kbps datarate as default but as soon as it was flashed, the sensors work flawless with your library. 
Probably you can add a way to make the library configurable and send an appropriate command to the stick if another bitrate or frequency is required (similar to FHEM). This could also add the Toogle command as described in the FHEM documentation.

Thanks for your work!

**Comment by hthiery** [comment]
Hi,
that shouldnt be a big issue. What commands (from the FHEM/jeelink sketch docu) do you need to configure your environment.

What do you think is a good interface for the pylacrosse API to make this available?

**Comment by deveth0** [comment]
hm, i think it would be very helpful to support at least a switch for frequency (e.g. 868295f) and bitrate (e.g. 1r):

``` 
<n>f     initial frequency in kHz (5 kHz steps, 860480 ... 879515)  (for RFM #1)
<n>r     use one of the possible data rates
```
Note: if r is 0,1 or 2, it sets one of the default rates, otherwise the given rate (17241r is the same as 0r)

Furthermore the toogle would be helpful for the scan option as it switches through the frequencies and allows to find more devices. Either use 10t by default or give a parameter which sets the time:
```
<n>t     0=no toggle, else interval in seconds (for RFM #1)
```

Most likely it's helpful to keep the naming for the parameters (although it's not very clear), so propably something like 
```
pylacrosse -d /dev/ttyUSB0 scan -t 10
pylacrosse -d /dev/ttyUSB0 scan -f 875000
pylacrosse -d /dev/ttyUSB0 scan -r 1
pylacrosse -d /dev/ttyUSB0 scan -r 8842
```
?

**Comment by hthiery** [comment]
Hi .. just pushed new version that should support all settings. Please test the new version and give some feedback. Then I will start integrate it to the homeassistant component.

**Comment by deveth0** [comment]
hey, sorry for the late response. I just checked out the latest version and reflashed the jeelink to the default firmware.
Either I'm not using it correct or there is something missing:
```
root@homeassistant:/home/pi# pylacrosse -r 9579  -v -d /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI03DAOB-if00-port0 scan
```
This does not result in any output. 
I would also assume that the info method returns the passed arguments:
```
root@homeassistant:/home/pi# pylacrosse -r 9579 -v -d /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI03DAOB-if00-port0 info
name:     LaCrosseITPlusReader
version:  10.1s
rfm1name: RFM69CW
rfm1frequency: 868300
rfm1datarate: 17241
rfm1toggleinterval: None
rfm1togglemask: None
```

**Comment by hthiery** [comment]
hmm ... realy strange. I justed check on my site and this seems to work. Could you please test other frequencies?

Could also check if you are able to connect to the jeelink via serial console and type the configre command directly?

`1r` or `9579r` and show the settings with `v`

**Comment by deveth0** [comment]
Sry my fault... 0.3.1 works now :)
```
root@homeassistant:/home/pi# python3 -m pip install --upgrade pylacrosse
Collecting pylacrosse
  Downloading https://www.piwheels.hostedpi.com/simple/pylacrosse/pylacrosse-0.3.1-py3-none-any.whl
Requirement already up-to-date: pyserial in /usr/local/lib/python3.5/dist-packages (from pylacrosse)
Installing collected packages: pylacrosse
  Found existing installation: pylacrosse 0.3
    Uninstalling pylacrosse-0.3:
      Successfully uninstalled pylacrosse-0.3
Successfully installed pylacrosse-0.3.1
root@homeassistant:/home/pi# pylacrosse -r 9579 -v -d /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI03DAOB-if00-port0 scan
id=8 t=19.800000 h=39 nbat=0 name=unknown
id=30 t=17.700000 h=43 nbat=0 name=unknown
id=21 t=20.700000 h=39 nbat=0 name=unknown
id=35 t=3.800000 h=80 nbat=0 name=unknown
```

I did some more tests and it looks really good, thanks!

**Comment by hthiery** [comment]
I also updated the home-assistant component and the new feature should be included in the upcoming release.

**Comment by deveth0** [comment]
Awesome, thank you!
