### ISSUE TITLE
Documentation refers to wrong config-file

### ISSUE THREAD

**Issue by ohessel** [hthiery/python-lacrosse#9]
The documentation says  to use '~/.lacrosse/known_devices.ini' to name the devices, the script itself uses: '~/.lacrosse/known_sensors.ini'

**Comment by hthiery** [comment]
indeed .. thank you ... could you please do a PR?

**Comment by ohessel** [comment]
Sure: https://github.com/hthiery/python-lacrosse/pull/10

**Comment by hthiery** [comment]
PR merged
